# Generated by Django 4.1.4 on 2022-12-10 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201207_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
